services:
  db:
    image: mysql:latest
    restart: always
    env_file:
      - ./env/${ENV}.env
    environment:
      MYSQL_ROOT_PASSWORD: rOOtPassword
      MYSQL_DATABASE: dockereval
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

  auth-app:
    build: ./Auth-app
    env_file:
      - ./env/${ENV}.env
    depends_on:
      - db
    ports:
      - 3000:3000

  api-app:
    build: ./Api-app
    env_file:
      - ./env/${ENV}.env
    depends_on:
      - db
      - auth-app
    ports:
      - 5000:5000

volumes:
  db_data:
