services:
  db:
    image: mysql:latest
    restart: always
    env_file:
      - ./env/${ENV}.env
    environment:
      MYSQL_ROOT_PASSWORD: rOOtPassword
      MYSQL_DATABASE: dockereval
    volumes:
      - db_data:/var/lib/mysql

  auth-app:
    build: ./Auth-app
    env_file:
      - ./env/${ENV}.env
    depends_on:
      - db

  api-app:
    build: ./Api-app
    env_file:
      - ./env/${ENV}.env
    depends_on:
      - db
      - auth-app

volumes:
  db_data:
